name: Release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  push:
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false

      # zizmor complains that 'v1' is a ref that can be provided by both the branch and tag namespaces.
      # specify that we want the v1 branch.
      - name: Set up Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # 1.295.0
        with:
          ruby-version: ruby

      - run: bundle install
        env:
          BUNDLE_FROZEN: true

      # zizmor complains that 'v1' is a ref that can be provided by both the branch and tag namespaces.
      # specify that we want the v1 branch.
      - uses: rubygems/release-gem@e9a6361a0b14562539327c2a02373edc56dd3169 # 1.1.4
