name: Release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  push:
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: true
          persist-credentials: false

      # zizmor complains that 'v1' is a ref that can be provided by both the branch and tag namespaces.
      # specify that we want the v1 branch.
      - name: Set up Ruby
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: ruby

      - run: bundle install
        env:
          BUNDLE_FROZEN: true

      # zizmor complains that 'v1' is a ref that can be provided by both the branch and tag namespaces.
      # specify that we want the v1 branch.
      - uses: rubygems/release-gem@f0d7faff26625599a847d40d9fa28ace24c2aacc # v1.3.0
