name: Run rubocop

on:
  push:
  pull_request:
  schedule:
    - cron: '3 22 * * SUN'

permissions: {}

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # zizmor complains that 'v1' is a ref that can be provided by both the branch and tag namespaces.
      # specify that we want the v1 branch.
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: 3.4

      - run: bundle install
        env:
          BUNDLE_FROZEN: true
      - run: bundle exec rake -t rubocop
