name: Run tests

on:
  push:
  pull_request:
  schedule:
    - cron: '3 23 * * SUN'

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version:
          [
            3.2,
            3.3,
            3.4,
            '4.0',
            jruby,
          ]
        exclude:
          - os: windows-latest
            version: jruby
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: true
          persist-credentials: false

      # zizmor complains that 'v1' is a ref that can be provided by both the branch and tag namespaces.
      # specify that we want the v1 branch.
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: ${{ matrix.version }}

      - run: bundle install
        env:
          BUNDLE_FROZEN: true
      - run: bundle exec rake -t test
